source: .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md']
keep_files:  ['.git', '.svn']
timezone: Europe/Brussels

# github overrides some values as follows
safe: true
lsi: false
rouge: true


redcloth:
  hard_breaks: false
